spring:
#  config:
#    activate:
#      on-profile: dev
  banner:
    location: classpath:banner/banner.txt
  main:
    banner-mode: console
logging:
  level:
    root: info
    org:
      springframework: warn
      boot: error
  pattern:
    console: '%n %d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg'