spring:
  profiles:
    active: database, console
  data:
    rest:
      base-path: ${BASE_PATH:/api}
  application:
    name: example-2

server:
  port: ${SERVER_PORT:8000}
  address: ${SERVER_ADDRESS:localhost}
