spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: usuario
    password: usuario
    driver-class-name: org.postgresql.Driver 
  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: create 
      #create 
      #create-drop 
      # validate 
      #none 
      #update
    show-sql: false 
    # show the updates on the sql on the console

